# Generated by Django 5.0 on 2025-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restrand', '0002_remove_user_lock_remove_user_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='team_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_image', models.ImageField(upload_to='team')),
                ('team_name', models.CharField(max_length=100)),
                ('team_description', models.TextField()),
            ],
        ),
    ]
